# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: spittet/ruby-postgresql

pipelines:
    default:
        - step:
            script: # Modify the commands below to build your repository.
                - echo "this is default config. does nothing"
                - ruby --version
    branches:
        master:
        - step:
            script:
                - echo "This script runs only on commit to the master branch."
                - ./heroku_deploy.sh
        fb-*:
        - step:
            script:
                - echo "this is feature branch"
                - ruby --version
                - bundler --version
                - bundle install
                - sudo apt-get update
                - sudo apt-get install nodejs -y
                - /etc/init.d/postgresql start
                - sudo -u postgres sh -c "createuser $DB_USER & createdb $TEST_DB"
                - sudo -u postgres psql -c "ALTER USER $DB_USER WITH PASSWORD $DB_PASSWORD"
                - mv ./config/database.yml.example ./config/database.yml
                - rake db:migrate
                - rspec
        dev:
        - step:
            script:
                - echo "this is feature branch"
                - ruby --version
                - bundler --version
                - bundle install
                - sudo apt-get update
                - sudo apt-get install nodejs -y
                - /etc/init.d/postgresql start
                - sudo -u postgres sh -c "createuser $DB_USER & createdb $TEST_DB"
                - sudo -u postgres psql -c "ALTER USER $DB_USER WITH PASSWORD $DB_PASSWORD"
                - mv ./config/database.yml.example ./config/database.yml
                - rake db:migrate
                - rspec